general:
  daemon: true
  sleep: 900
  state_path: /app/state.db

credentials:
  - name: twitter-auth
    api_key: foo
    api_secret_key: bar
    access_token: foo
    access_token_secret: bar

sources:
  - name: retrieve_member
    module: twitter
    credentials: twitter-auth
    owner_screen_name: retrieve_member
    list_id: 1304400520421892096

operators:
  - name: sqlite-db
    module: sqlite
    filename: /app/artifacts.db
